language: cpp
dist: xenial
sudo: required
group: beta

before_install:
  - sudo apt-get -y install libsfml-dev

compiler:
  - gcc
  - clang
script:
  - mkdir build
  - cd build
  - cmake ..
  - make 
